Sims/Models/Quest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Sims.Models
{
    public class Quest
    {
        [Key]
        public Guid QuestID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }
        [Required]
        [Range(0.01,double.MaxValue,ErrorMessage ="Please enter a positive value")]
        public double Cost { get; set; }
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive value")]
        public double Reward { get; set; }
    }
}

Sims/Controllers/QuestController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class QuestController : Controller
    {
        private IRepository repository;
        public QuestController(IRepository repo)
        {
            repository = repo;
        }
        
        public ActionResult Index() => View(repository.Quests);

        public ViewResult Edit(Guid questID) =>
           View(repository.Quests
          .FirstOrDefault(q => q.QuestID == questID));

        [HttpPost]
        public IActionResult Edit(Quest quest)
        {

            if (ModelState.IsValid)
            {
                repository.SaveQuest(quest);
                TempData["message"] = $"{quest.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(quest);
            }
        }
        public ViewResult Create() => View("Edit", new Quest());

        [HttpPost]
        public IActionResult Delete(Guid questID)
        {
            Quest deletedQuest = repository.DeleteQuest(questID);
            if (deletedQuest != null)
            {
                TempData["message"] = $"{deletedQuest.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
        
    }
}

Sims/Views/Quest/Edit.cshtml
@model Quest
@{
    ViewBag.Title = "Edit Quest";
    Layout = "_AdminLayout";
}
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="QuestID" />

    <div class="form-group">
        <label asp-for="Name"></label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Cost"></label>
        <div><span asp-validation-for="Cost" class="text-danger"></span></div>
        <input asp-for="Cost" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Reward"></label>
        <div><span asp-validation-for="Reward" class="text-danger"></span></div>
        <input asp-for="Reward" class="form-control" />
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Sims/Views/Quest/Index.cshtml
@model IEnumerable<Quest>
@{
    ViewBag.Title = "All Quests";
    Layout = "_AdminLayout";

}
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th>Cost</th>
        <th>Reward</th>
        <th class="text-center"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.QuestID</td>
            <td>
                @item.Name
            </td>
            <td>@item.Cost</td>
            <td>@item.Reward</td>

            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a asp-controller="Quest" asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-QuestID="@item.QuestID">
                        Edit
                    </a>
                    <input type="hidden" name="QuestID" value="@item.QuestID" />
                    <button type="submit" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Quest</a>
</div>