Sims/Models/Relations/SimLives.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Sims.Models.Relations
{
    public class SimLives
    {
        [Key]
        public Guid SimID { get; set; }
        [ForeignKey("SimID")]
        public Sim Sim { get; set; }

        
        public Guid DomesticUnitID { get; set; }
        [ForeignKey("DomesticUnitID")]
        public DomesticUnit DomesticUnit { get; set; }
    }
}
    

Sims/Models/Sim.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;



namespace Sims.Models
{
    public class Sim
    {
        [Key]
        public Guid SimID { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a last name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter a money value")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive value")]
        public double Money { get; set; }

        public string Gender { get; set; }
        [Display(Name = "Life Stage")]
        public string LifeStage { get; set; }

    }
}

Sims/Models/Skill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Sims.Models
{
    public class Skill
    {
        [Key]
        public Guid SkillID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Description { get; set; }
    }
}

Sims/Controllers/SimController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class SimController : Controller
    {
        private IRepository repository;
        public SimController(IRepository repo)
        {
            repository = repo;
        }

        public ViewResult Profile(Guid id) => View(
            repository.Sims
            .FirstOrDefault(s => s.SimID == id));



        public ViewResult ChooseDomesticUnit(Guid id)
        {
            SimDomesticUnitViewModel simDomesticUnit = new SimDomesticUnitViewModel
            {
                Sim = repository.Sims.FirstOrDefault(s => s.SimID == id)
            };

            SimLives simLives = repository.SimLivesTable
                .FirstOrDefault(s => s.SimID == simDomesticUnit.Sim.SimID);

            simDomesticUnit.DomesticUnits = simLives == null ? repository.DomesticUnits : repository.DomesticUnits.Where(d => d.DomesticUnitID != simLives.DomesticUnitID);

            if (simLives != null)
            {
                DomesticUnit domesticUnit = repository.DomesticUnits
                    .FirstOrDefault(d => d.DomesticUnitID == simLives.DomesticUnitID);
                simDomesticUnit.CurrentDomesticUnitName = domesticUnit.Name;

            }

            return View(simDomesticUnit);
        }

        [HttpPost]
        public ActionResult ChooseDomesticUnit(SimDomesticUnitViewModel simDomesticUnit)
        {
            SimLives simLives = new SimLives
            {
                SimID = simDomesticUnit.Sim.SimID,
                DomesticUnitID = simDomesticUnit.DomesticUnitID
            };
            simLives.Sim = repository.Sims
                .FirstOrDefault(s => s.SimID == simLives.SimID);
            simLives.DomesticUnit = repository.DomesticUnits
                .FirstOrDefault(d => d.DomesticUnitID == simDomesticUnit.DomesticUnitID);

            if (ModelState.IsValid)
            {
                repository.SaveSimLives(simLives);
                TempData["message"] = $"{simLives.Sim.Name} now lives in {simLives.DomesticUnit.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                //if enters here there is something wrong with the data values
                return View(simDomesticUnit);
            }
        }

        public ViewResult ChooseProfession(Guid id)
        {

            SimProfessionViewModel simProfession = new SimProfessionViewModel
            {
                Sim = repository.Sims.FirstOrDefault(s => s.SimID == id)
            };
            Exercise exercise = repository.Exercises
                .FirstOrDefault(e => e.SimID == simProfession.Sim.SimID);
            simProfession.Professions = exercise == null ? repository.Professions : repository.Professions.Where(p => p.ProfessionID != exercise.ProfessionID);

            if (exercise != null)
            {
                Profession profession = repository.Professions
                    .FirstOrDefault(p => p.ProfessionID == exercise.ProfessionID);
                simProfession.CurrentProfessionName = profession.Name;
                simProfession.Level = exercise.Level;
            }


            return View(simProfession);
        }

        [HttpPost]
        public ActionResult ChooseProfession(SimProfessionViewModel simProfession)
        {
            Exercise exercise = new Exercise
            {
                SimID = simProfession.Sim.SimID,
                ProfessionID = simProfession.ProfessionID,
                Level = 1
            };
            exercise.Sim = repository.Sims
                .FirstOrDefault(s => s.SimID == exercise.SimID);
            exercise.Profession = repository.Professions
                .FirstOrDefault(p => p.ProfessionID == exercise.ProfessionID);

            if (ModelState.IsValid)
            {
                repository.SaveExercise(exercise);
                TempData["message"] = $"{exercise.Sim.Name} is now a level 1 {exercise.Profession.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                //if enters here there is something wrong with the data values
                return View(simProfession);
            }
        }

        public ViewResult Skills(Guid simID) => View(repository.SimSkillsTable.Where(s => s.SimID == simID));

        public ViewResult Activities(Guid id)
        {
            SimActivityViewModel viewModel = new SimActivityViewModel
            {
                Activities = repository.Activities,
                Sim = repository.Sims.FirstOrDefault(s => s.SimID == id)
            };
            return View(viewModel);
        }

        /*
        [HttpPost]
        public ActionResult PerformActivity(SimActivityViewModel viewModel)
        {
            var requirements = repository.ActivityRequiresSkillTable
                .Where(a => a.ActivityID == viewModel.ActivityID);

            var skills = repository.SimSkillsTable
                .Where(s => s.SimID == viewModel.Sim.SimID);

        }
        */
       
        /*
        public ViewResult FilterForm()
        {
            SimSearchFilterForm form = new SimSearchFilterForm
            {
                Professions = repository.Professions,
                Skills = repository.Skills
            };
            return View(form);
        }
        public ActionResult List(SimSearchFilterForm form)
        {
            var simPropsCheck = repository.Sims
                .Where(s =>
                (form.Sim.Name != null && form.Sim.Name == s.Name) || (form.Sim.Name == null && s.Name != null))
                .Where(s =>
                (form.Sim.LastName != null && form.Sim.LastName == s.LastName) || (form.Sim.LastName == null && s.LastName != null))
                .ToList();

            var professionCheck = new List<Sim>();
            if (form.ProfessionID != 0)
            {
                foreach (Sim sim in simPropsCheck)
                    if (repository.Exercises.FirstOrDefault(e => e.SimID == sim.SimID && e.ProfessionID == form.ProfessionID) != null)
                        professionCheck.Add(sim);
            }
            else professionCheck = simPropsCheck;

            var bySkillPoints = new List<SimSkillPoints>();
            var simsBySkillPoints = new List<Sim>();
            if (form.SkillID != 0)
            {
                foreach (Sim sim in professionCheck)
                {
                    var simPoints = repository.SimSkills.FirstOrDefault(s => s.SimID == sim.SimID && s.SkillID == form.SkillID);
                    if (simPoints == null)
                        bySkillPoints.Add(new SimSkillPoints
                        {
                            Sim = sim,
                            SkillPoints = 0
                        });
                    else
                        bySkillPoints.Add(new SimSkillPoints
                        {
                            Sim = sim,
                            SkillPoints = simPoints.Points
                        });
                }
                bySkillPoints.OrderByDescending(s => s.SkillPoints);
                for (int i = 0; i < bySkillPoints.Count; i++)
                    simsBySkillPoints.Add(bySkillPoints[i].Sim);
            }
            else simsBySkillPoints = professionCheck;
            
            simsBySkillPoints.
            
            return View(professionCheck);
            
            
        }
        
        */  
        

        public ViewResult Index() => View(repository.Sims);
        
        public ViewResult Edit(Guid simID) =>
           View(repository.Sims
               .FirstOrDefault(s => s.SimID == simID));

        [HttpPost]
        public IActionResult Edit(Sim sim)
        {

            if (ModelState.IsValid)
            {
                repository.SaveSim(sim);
                TempData["message"] = $"{sim.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                 //if enters here there is something wrong with the data values
                return View(sim);
            }
        }
        public ViewResult Create() => View("Edit", new Sim());
         
        [HttpPost]
        public IActionResult Delete(Guid simID)
        {
            Sim deletedSim = repository.DeleteSim(simID);
            if (deletedSim != null)
            {
                TempData["message"] = $"{deletedSim.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
        
    }
}

Sims/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class SkillController : Controller
    {
        private IRepository repository;
        public SkillController(IRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index() => View(repository.Skills);

        public ViewResult Edit(Guid skillID) =>
         View(repository.Skills
             .FirstOrDefault(s => s.SkillID == skillID));

        [HttpPost]
        public IActionResult Edit(Skill skill)
        {

            if (ModelState.IsValid)
            {
                repository.SaveSkill(skill);
                TempData["message"] = $"{skill.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(skill);
            }
        }

        public ViewResult Create() => View("Edit", new Skill());

        /*
        [HttpPost]
        public IActionResult Delete(int skillID)
        {
            Skill deletedSkill = repository.DeleteSkill(skillID);
            if (deletedSkill != null)
            {
                TempData["message"] = $"{deletedSkill.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
        */
    }
}

Sims/Views/Sim/Activities.cshtml
@model SimActivityViewModel


@using (Html.BeginForm("PerformActivity", "Sim", FormMethod.Post, new { id = "performActivity" }))
{
    <div class="form-group margin">
        @Html.LabelFor(p => p.ActivityID)
        @Html.DropDownListFor(p => p.ActivityID, new SelectList(Model.Activities, "ActivityID", "Name"), new { @class = "form-control" })
    </div>

    @Html.HiddenFor(p => p.Sim.SimID)
    @Html.HiddenFor(p => p.Sim.Name)
    @Html.HiddenFor(p => p.Sim.LastName)
    @Html.HiddenFor(p => p.Sim.Gender)
    @Html.HiddenFor(p => p.Sim.Money)
    @Html.HiddenFor(p => p.Sim.LifeStage)
    

    <button type="submit" class="btn btn-primary">Perform Activity</button>
    <a asp-action="Profile" asp-route-id="@Model.Sim.SimID" class="btn btn-secondary">Cancel</a>

}

Sims/Views/Sim/ChooseDomesticUnit.cshtml
@model SimDomesticUnitViewModel


@if (Model.CurrentDomesticUnitName != null)
{
    <div class="margin">
        <p>@Model.Sim.Name currently lives in @Model.CurrentDomesticUnitName</p>
    </div>
}
@using (Html.BeginForm("ChooseDomesticUnit", "Sim", FormMethod.Post, new { id = "simDomesticUnit" }))
{
    <div class="form-group margin">
        @Html.LabelFor(p => p.DomesticUnitID)
        @Html.DropDownListFor(p => p.DomesticUnitID, new SelectList(Model.DomesticUnits, "DomesticUnitID", "Name"), new { @class = "form-control" })
    </div>

    @Html.HiddenFor(p => p.Sim.SimID)
    @Html.HiddenFor(p => p.Sim.Name)
    @Html.HiddenFor(p => p.Sim.LastName)
    @Html.HiddenFor(p => p.Sim.Gender)
    @Html.HiddenFor(p => p.Sim.Money)
    @Html.HiddenFor(p => p.Sim.LifeStage)


    <button type="submit" class="btn btn-primary">Accept</button>
    <a asp-action="Profile" asp-route-id="@Model.Sim.SimID" class="btn btn-secondary">Cancel</a>

}

Sims/Views/Sim/ChooseProfession.cshtml
@model SimProfessionViewModel


@if (Model.CurrentProfessionName != null)
{   
    <div class="margin">
    <p>
        @Model.Sim.Name is currently a level @Model.Level @Model.CurrentProfessionName</p>
    </div>
}
@using (Html.BeginForm("ChooseProfession", "Sim", FormMethod.Post, new { id = "simProfession" }))
{
    <div class="form-group margin">
        @Html.LabelFor(p => p.ProfessionID)
        @Html.DropDownListFor(p => p.ProfessionID, new SelectList(Model.Professions, "ProfessionID", "Name"), new { @class = "form-control" })
    </div>

    @Html.HiddenFor(p => p.Sim.SimID)
    @Html.HiddenFor(p => p.Sim.Name)
    @Html.HiddenFor(p => p.Sim.LastName)
    @Html.HiddenFor(p => p.Sim.Gender)
    @Html.HiddenFor(p => p.Sim.Money)
    @Html.HiddenFor(p => p.Sim.LifeStage)
    

    <button type="submit" class="btn btn-primary">Accept</button>
    <a asp-action="Profile" asp-route-id="@Model.Sim.SimID" class="btn btn-secondary">Cancel</a>

}

Sims/Views/Sim/Edit.cshtml
@model Sim
@{
    ViewBag.Title = "Edit Sim";
}
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="SimID" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <div><span asp-validation-for="LastName" class="text-danger"></span></div>
        <input asp-for="LastName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Money"></label>
        <div><span asp-validation-for="Money" class="text-danger"></span></div>
        <input asp-for="Money" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Gender"></label>
        <select asp-for="Gender" class="form-control">
            <option>Male</option>
            <option>Female</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="LifeStage"></label>
        <select asp-for="LifeStage" class="form-control">
            <option>Infant</option>
            <option>Teenager</option>
            <option>Young Adult</option>
            <option>Adult</option>
            <option>Elder</option>
        </select>
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Sims/Views/Sim/FilterForm.cshtml
@model SimSearchFilterForm
<h2>Fill the spaces so you filter the list of Sims to be displayed</h2>

@using (Html.BeginForm("List", "Sim"))
{
<div class="form-group">
    @Html.LabelFor(m => m.Sim.Name)
    @Html.ValidationMessageFor(m => m.Sim.Name)
    @Html.TextBoxFor(m => m.Sim.Name, new { @class = "form-control" })
</div>

    <div class="form-group">
        @Html.LabelFor(m => m.Sim.LastName)
        @Html.ValidationMessageFor(m => m.Sim.LastName)
        @Html.TextBoxFor(m => m.Sim.LastName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.ProfessionID)
        @Html.DropDownListFor(p => p.ProfessionID, new SelectList(Model.Professions, "ProfessionID", "Name"), "", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(p => p.SkillID)
        @Html.DropDownListFor(p => p.SkillID, new SelectList(Model.Skills, "SkillID", "Name"), "", new { @class = "form-control" })
    </div>
   
    <div class="form-group">
        @Html.LabelFor(m => m.FirstHowMany)
        @Html.ValidationMessageFor(m => m.FirstHowMany)
        @Html.TextBoxFor(m => m.FirstHowMany, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
}

Sims/Views/Sim/Index.cshtml
@model IEnumerable<Sim>
@{
    ViewBag.Title = "All Sims";

}

<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th>Last Name</th>
        <th>Money</th>
        <th>Gender</th>
        <th>Life Stage</th>
        <th class="text-center"></th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td class="text-right">@item.SimID</td>
    <td>
        <a class="nav-link" asp-controller="Sim" asp-action="Profile" asp-route-id="@item.SimID">@item.Name</a>
    </td>
    <td>@item.LastName</td>
    <td>@item.Money.ToString("c")</td>
    <td>@item.Gender</td>
    <td>@item.LifeStage</td>
    <td class="text-center">
        <form asp-action="Delete" method="post">
            <a asp-action="Edit" class="btn btn-sm btn-warning"
               asp-route-SimID="@item.SimID">
                Edit
            </a>
            <input type="hidden" name="SimID" value="@item.SimID" />
            <button type="submit" class="btn btn-danger btn-sm">
                Delete
            </button>
        </form>
    </td>
</tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Sims</a>
    <a asp-action="FilterForm" class="btn btn-secondary">Search</a>
</div>

Sims/Views/Sim/List.cshtml
@model IEnumerable<Sim>

<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th>Last Name</th>
        <th>Money</th>
        <th>Gender</th>
        <th>Life Stage</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.SimID</td>
            <td>
                <a class="nav-link" asp-controller="Sim" asp-action="Profile" asp-route-id="@item.SimID">@item.Name</a>
            </td>
            <td>@item.LastName</td>
            <td>@item.Money.ToString("c")</td>
            <td>@item.Gender</td>
            <td>@item.LifeStage</td>
        </tr>
    }
</table>

Sims/Views/Sim/Profile.cshtml
@model Sim
    <div class="jumbotron margin" >
        <h1 class="display-3">@Model.Name @Model.LastName</h1>
        <p class="lead">Sim of @Model.Gender gender</p>
        <hr class="my-4">
        <p>Currently owns @Model.Money simoleons</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" asp-controller="Sim" asp-action="ChooseProfession" asp-route-id="@Model.SimID" role="button">Profession</a>
            <a class="btn btn-secondary btn-lg" asp-controller="Sim" asp-action="ChooseDomesticUnit" asp-route-id="@Model.SimID" role="button">Domestic Unit</a>
            <a class="btn btn-primary btn-lg" asp-controller="Sim" asp-action="Skills" asp-route-id="@Model.SimID" role="button">Skills</a>
            <a class="btn btn-secondary btn-lg space" asp-controller="Sim" asp-action="Activities" asp-route-id="@Model.SimID" role="button">Activities</a>
        </p>
    </div>

Sims/Views/Sim/Skills.cshtml
@model IEnumerable<SimSkills>

@if (Model.Count() == 0)
{
    <div class="center verCenter">
        <p>This Sim doesn't have ability points for any skill :(</p>
    </div>
}
else
{
    <table class="table table-striped table-bordered table-sm">
        <tr>
            
            <th>Skill</th>
            <th>Level</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Skill.Name</td>
                <td>@item.Points</td>
            </tr>
        }
    </table>
}