Sims/Models/Neighborhood.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Sims.Models
{
    public class Neighborhood
    {
        [Key]
        public Guid NeighborhoodID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Description { get; set; }
    }
}

Sims/Models/Place.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Sims.Models
{
    public class Place
    {
        [Key]
        public Guid PlaceID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }
        [Range(0,double.MaxValue,ErrorMessage = "Please enter a non-negative number")]
        public double Cost { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Description { get; set; }
    }
}

Sims/Controllers/NeighborhoodController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class NeighborhoodController : Controller
    {
        private IRepository repository;
        public NeighborhoodController(IRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult Index() => View(repository.Neighborhoods);

        public ViewResult Edit(Guid neighborhoodID) =>
         View(repository.Neighborhoods
             .FirstOrDefault(n => n.NeighborhoodID == neighborhoodID));

        [HttpPost]
        public IActionResult Edit(Neighborhood neighborhood)
        {

            if (ModelState.IsValid)
            {
                repository.SaveNeighborhood(neighborhood);
                TempData["message"] = $"{neighborhood.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(neighborhood);
            }
        }

        public ViewResult Create() => View("Edit", new Neighborhood());

        [HttpPost]
        public IActionResult Delete(Guid neighborhoodID)
        {
            Neighborhood deletedNeighborhood = repository.DeleteNeighborhood(neighborhoodID);
            if (deletedNeighborhood != null)
            {
                TempData["message"] = $"{deletedNeighborhood.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
       
    }
}

Sims/Controllers/PlaceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class PlaceController : Controller
    {
        private IRepository repository;
        public PlaceController(IRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult Profile(Guid id) => View(
            repository.Places
            .FirstOrDefault(p => p.PlaceID == id));

        public ViewResult Index() => View(repository.Places);

        public ViewResult Edit(Guid placeID) =>
         View(repository.Places
             .FirstOrDefault(p =>p.PlaceID == placeID));

        [HttpPost]
        public IActionResult Edit(Place place)
        {

            if (ModelState.IsValid)
            {
                repository.SavePlace(place);
                TempData["message"] = $"{place.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(place);
            }
        }

        public ViewResult Create() => View("Edit", new Place());

        [HttpPost]
        public IActionResult Delete(Guid placeID)
        {
            Place deletedPlace = repository.DeletePlace(placeID);
            if (deletedPlace != null)
            {
                TempData["message"] = $"{deletedPlace.Name} was deleted";
            }
            return RedirectToAction("Index");
        }

        public ViewResult Neighborhood(Guid id)
        {
            PlaceNeighborhoodViewModel viewModel = new PlaceNeighborhoodViewModel
            {
                Place = repository.Places.FirstOrDefault(p => p.PlaceID == id)
            };
            NeighborhoodPlaces relation = repository.NeighborhoodPlacesTable
                .FirstOrDefault(e => e.PlaceID == viewModel.Place.PlaceID);
           
            viewModel.Neighborhoods = relation == null ? repository.Neighborhoods : repository.Neighborhoods.Where(n => n.NeighborhoodID != relation.NeighborhoodID);

            if (relation != null)
            {
                Neighborhood neighborhood = repository.Neighborhoods
                    .FirstOrDefault(n => n.NeighborhoodID == relation.NeighborhoodID);
                viewModel.CurrentNeighborhoodName = neighborhood.Name;
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Neighborhood(PlaceNeighborhoodViewModel viewModel)
        {
            NeighborhoodPlaces relation = new NeighborhoodPlaces
            {
                PlaceID = viewModel.Place.PlaceID,
                NeighborhoodID = viewModel.NeighborhoodID
            };
            relation.Place = repository.Places
                .FirstOrDefault(p => p.PlaceID == relation.PlaceID);
            relation.Neighborhood = repository.Neighborhoods
                .FirstOrDefault(n => n.NeighborhoodID == relation.NeighborhoodID);

            if (ModelState.IsValid)
            {
                repository.SaveNeighborhoodPlace(relation);
                TempData["message"] = $"{relation.Place.Name} is now located in {relation.Neighborhood.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(relation);
            }
        }
        
    }
}

Sims/Views/Place/Edit.cshtml
@model Place
@{
    ViewBag.Title = "Edit Place";
    Layout = "_AdminLayout";
}
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="PlaceID" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Cost"></label>
        <div><span asp-validation-for="Cost" class="text-danger"></span></div>
        <input asp-for="Cost" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <div><span asp-validation-for="Description" class="text-danger"></span></div>
        <input asp-for="Description" class="form-control" />
    </div>

    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Sims/Views/Place/Index.cshtml
@model IEnumerable<Place>
@{
    ViewBag.Title = "All Places";
    Layout = "_AdminLayout";

}
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th>Cost</th>
        <th>Description</th>
        <th class="text-center"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.PlaceID</td>
            <td>
                <a class="nav-link" asp-controller="Place" asp-action="Profile" asp-route-id="@item.PlaceID">@item.Name</a>
            </td>
            <td>@item.Cost</td>
            <td>@item.Description</td>

            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-PlaceID="@item.PlaceID">
                        Edit
                    </a>
                    <input type="hidden" name="PlaceID" value="@item.PlaceID" />
                    <button type="submit" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Place</a>
</div>

Sims/Views/Place/Neighborhood.cshtml
@model PlaceNeighborhoodViewModel


@if (Model.CurrentNeighborhoodName != null)
{
    <div class="margin">
        <p>
            @Model.Place.Name is currently located in @Model.CurrentNeighborhoodName
        </p>
    </div>
}
@using (Html.BeginForm("Neighborhood", "Place", FormMethod.Post, new { id = "palceNeighborhood" }))
{
    <div class="form-group margin">
        @Html.LabelFor(n => n.NeighborhoodID)
        @Html.DropDownListFor(n => n.NeighborhoodID, new SelectList(Model.Neighborhoods, "NeighborhoodID", "Name"), new { @class = "form-control" })
    </div>

    @Html.HiddenFor(p => p.Place.PlaceID)
    @Html.HiddenFor(p => p.Place.Name)
    @Html.HiddenFor(p => p.Place.Cost)
    @Html.HiddenFor(p => p.Place.Description)


    <button type="submit" class="btn btn-primary">Accept</button>
    <a asp-action="Profile" asp-route-id="@Model.Place.PlaceID" class="btn btn-secondary">Cancel</a>

}

Sims/Views/Place/Profile.cshtml
@model Place
<div class="jumbotron margin">
    <h1 class="display-3">@Model.Name</h1>
    <p class="lead">This place's services cost @Model.Cost simoleons</p>
    <hr class="my-4">
    <p>@Model.Description</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg space" asp-controller="Place" asp-action="Neighborhood" asp-route-id="@Model.PlaceID" role="button">Neighborhood</a>
    </p>
</div>