Sims/Models/DomesticUnit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Sims.Models
{
    public class DomesticUnit
    {
        [Key]
        public Guid DomesticUnitID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name{ get; set; }
        [Required(ErrorMessage = "Please enter a number of rooms")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter a non-negative value")]
        [Display(Name ="Number of rooms")]
        public int RoomNumber { get; set; }
        [Required(ErrorMessage = "Please enter a number of bathrooms")]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter a non-negative value")]
        [Display(Name = "Number of bathrooms")]
        public int BathroomNumber { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Description { get; set; }
   }
}

Sims/Models/Neighborhood.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Sims.Models
{
    public class Neighborhood
    {
        [Key]
        public Guid NeighborhoodID { get; set; }
        [Required(ErrorMessage = "Please enter a name")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(127, ErrorMessage = "Limit of characters(127) exceeded")]
        public string Description { get; set; }
    }
}

Sims/Controllers/DomesticUnitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class DomesticUnitController : Controller
    {
        private IRepository repository;
        public DomesticUnitController(IRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult Profile(Guid id) => View(
           repository.DomesticUnits
           .FirstOrDefault(d => d.DomesticUnitID == id));

        public ViewResult Index() => View(repository.DomesticUnits);

        public ViewResult Edit(Guid domesticUnitID) =>
         View(repository.DomesticUnits
             .FirstOrDefault(d => d.DomesticUnitID == domesticUnitID));

        [HttpPost]
        public IActionResult Edit(DomesticUnit domesticUnit)
        {

            if (ModelState.IsValid)
            {
                repository.SaveDomesticUnit(domesticUnit);
                TempData["message"] = $"{domesticUnit.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(domesticUnit);
            }
        }

        public ViewResult Create() => View("Edit", new DomesticUnit());

        [HttpPost]
        public IActionResult Delete(Guid domesticUnitID)
        {
            DomesticUnit deletedDomesticUnit = repository.DeleteDomesticUnit(domesticUnitID);
            if (deletedDomesticUnit != null)
            {
                TempData["message"] = $"{deletedDomesticUnit.Name} was deleted";
            }
            return RedirectToAction("Index");
        }

        public ViewResult Neighborhood(Guid id)
        {
            DomesticUnitNeighborhoodViewModel viewModel = new DomesticUnitNeighborhoodViewModel
            {
                DomesticUnit = repository.DomesticUnits.FirstOrDefault(d => d.DomesticUnitID == id)
            };
            NeighborhoodDomesticUnits relation = repository.NeighborhoodDomesticUnitsTable
                .FirstOrDefault(e => e.DomesticUnitID == viewModel.DomesticUnit.DomesticUnitID);
            viewModel.Neighborhoods = relation == null ? repository.Neighborhoods : repository.Neighborhoods.Where(n => n.NeighborhoodID != relation.NeighborhoodID);

            if (relation != null)
            {
                Neighborhood neighborhood = repository.Neighborhoods
                    .FirstOrDefault(n => n.NeighborhoodID == relation.NeighborhoodID);
                viewModel.CurrentNeighborhoodName = neighborhood.Name;
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Neighborhood(DomesticUnitNeighborhoodViewModel viewModel)
        {
            NeighborhoodDomesticUnits relation = new NeighborhoodDomesticUnits
            {
                DomesticUnitID = viewModel.DomesticUnit.DomesticUnitID,
                NeighborhoodID = viewModel.NeighborhoodID
            };
            relation.DomesticUnit = repository.DomesticUnits
                .FirstOrDefault(d => d.DomesticUnitID == relation.DomesticUnitID);
            relation.Neighborhood = repository.Neighborhoods
                .FirstOrDefault(n => n.NeighborhoodID == relation.NeighborhoodID);

            if (ModelState.IsValid)
            {
                repository.SaveNeighborhoodDomesticUnit(relation);
                TempData["message"] = $"{relation.DomesticUnit.Name} is now located in {relation.Neighborhood.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(relation);
            }
        }
        
    }
}

Sims/Controllers/NeighborhoodController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Sims.Models;
using Sims.Models.Relations;
using Sims.Models.ViewModels;
using Sims.Models.Data;

namespace Sims.Controllers
{
    public class NeighborhoodController : Controller
    {
        private IRepository repository;
        public NeighborhoodController(IRepository repo)
        {
            repository = repo;
        }
        
        public ViewResult Index() => View(repository.Neighborhoods);

        public ViewResult Edit(Guid neighborhoodID) =>
         View(repository.Neighborhoods
             .FirstOrDefault(n => n.NeighborhoodID == neighborhoodID));

        [HttpPost]
        public IActionResult Edit(Neighborhood neighborhood)
        {

            if (ModelState.IsValid)
            {
                repository.SaveNeighborhood(neighborhood);
                TempData["message"] = $"{neighborhood.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // if enters here there is something wrong with the data values
                return View(neighborhood);
            }
        }

        public ViewResult Create() => View("Edit", new Neighborhood());

        [HttpPost]
        public IActionResult Delete(Guid neighborhoodID)
        {
            Neighborhood deletedNeighborhood = repository.DeleteNeighborhood(neighborhoodID);
            if (deletedNeighborhood != null)
            {
                TempData["message"] = $"{deletedNeighborhood.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
       
    }
}

Sims/Views/DomesticUnit/Edit.cshtml
@model DomesticUnit
@{
    ViewBag.Title = "Edit Domestic Unit";
    Layout = "_AdminLayout";
}
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="DomesticUnitID" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <div><span asp-validation-for="Name" class="text-danger"></span></div>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="RoomNumber"></label>
        <div><span asp-validation-for="RoomNumber" class="text-danger"></span></div>
        <input asp-for="RoomNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="BathroomNumber"></label>
        <div><span asp-validation-for="BathroomNumber" class="text-danger"></span></div>
        <input asp-for="BathroomNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <div><span asp-validation-for="Description" class="text-danger"></span></div>
        <input asp-for="Description" class="form-control" />
    </div>


    <div class="text-center">
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

Sims/Views/DomesticUnit/Index.cshtml
@model IEnumerable<DomesticUnit>
@{
    ViewBag.Title = "All Domestic Units";


}
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Name</th>
        <th>Rooms</th>
        <th>Bathrooms</th>
        <th>Description</th>
        <th class="text-center"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="text-right">@item.DomesticUnitID</td>
            <td>
            <a class="nav-link" asp-controller="DomesticUnit" asp-action="Profile" asp-route-id="@item.DomesticUnitID">@item.Name</a>
            </td>
            <td>@item.RoomNumber</td>
            <td>@item.BathroomNumber</td>
            <td>@item.Description</td>
            
            <td class="text-center">
                <form asp-action="Delete" method="post">
                    <a asp-action="Edit" class="btn btn-sm btn-warning"
                       asp-route-DomesticUnitID="@item.DomesticUnitID">
                        Edit
                    </a>
                    <input type="hidden" name="DomesticUnitID" value="@item.DomesticUnitID" />
                    <button type="submit" class="btn btn-danger btn-sm">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <a asp-action="Create" class="btn btn-primary">Add Domestic Unit</a>
</div>

Sims/Views/DomesticUnit/Neighborhood.cshtml
@model DomesticUnitNeighborhoodViewModel


@if (Model.CurrentNeighborhoodName != null)
{
    <div class="margin">
        <p>
            @Model.DomesticUnit.Name is currently located in @Model.CurrentNeighborhoodName
        </p>
    </div>
}
@using (Html.BeginForm("Neighborhood", "DomesticUnit", FormMethod.Post, new { id = "domesticUnitNeighborhood" }))
{
    <div class="form-group margin">
        @Html.LabelFor(n => n.NeighborhoodID)
        @Html.DropDownListFor(n => n.NeighborhoodID, new SelectList(Model.Neighborhoods, "NeighborhoodID", "Name"), new { @class = "form-control" })
    </div>

    @Html.HiddenFor(p => p.DomesticUnit.DomesticUnitID)
    @Html.HiddenFor(p => p.DomesticUnit.Name)
    @Html.HiddenFor(p => p.DomesticUnit.RoomNumber)
    @Html.HiddenFor(p => p.DomesticUnit.BathroomNumber)
    @Html.HiddenFor(p => p.DomesticUnit.Description)


    <button type="submit" class="btn btn-primary">Accept</button>
    <a asp-action="Profile" asp-route-id="@Model.DomesticUnit.DomesticUnitID" class="btn btn-secondary">Cancel</a>

}

Sims/Views/DomesticUnit/Profile.cshtml
@model DomesticUnit
<div class="jumbotron margin">
    <h1 class="display-3">@Model.Name</h1>
    <p class="lead">This domestic unit has @Model.RoomNumber rooms and @Model.BathroomNumber bathrooms</p>
    <hr class="my-4">
    <p>@Model.Description</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg space" asp-controller="DomesticUnit" asp-action="Neighborhood" asp-route-id="@Model.DomesticUnitID" role="button">Neighborhood</a>
    </p>
</div>